// <auto-generated />
namespace EventHandlingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DbSets_Edited_Names : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbSets_Edited_Names));
        
        string IMigrationMetadata.Id
        {
            get { return "201906201315247_DbSets_Edited_Names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
